### ISSUE TITLE
For some IFSC code, city, state and district are not coming.

### ISSUE THREAD

**Issue by karandesai28** [razorpay/ifsc#107]
For example: DEUT0796DEL 
Here city, state and district is not coming in response. It should have address details if it has a valid IFSC ideally. Can you please look into this.

Thanks.

**Comment by captn3m0** [comment]
This should automatically get corrected in the next release.

**Comment by karandesai28** [comment]
Great.
Thanks for the update. When is the next release expected? Also would there be any impact due to merger of Vijaya, Dena and Baroda Banks?
