### ISSUE TITLE
State name incorrect for some IFSC codes

### ISSUE THREAD

**Issue by anky3** [razorpay/ifsc#108]
When I'm querying for IFSC code of banks in **CHHATTISGARH** state, it returns an incorrect state name.

### Example 1: SBIN0010147
Branch Name: W R S COLONY RAIPUR
Address: W R S COLONY  SEC RAILWAY  RAIPUR  CHATTISGARH  492001
City: **BHOPAL** *(Incorrect, It should be RAIPUR)*
District: RAIPUR
State: **MADHYA PRADESH** *(Incorrect, It should be CHHATTISGARH)*

### Example 2: SBIN0012141
Branch Name: COLLECTORATE, MAHASAMUND
Address: MAHASAMUND COLLECTORATE ROAD,GOURAV PATH,DISTMAHASAMUND493445
City: MAHASAMUND
District: MAHASAMUND
State: **CHANDIGARH** *(Incorrect, It should be CHATTISGARH)*

### Example 3: SBIN0017728
Branch Name: RAJEEV NAGAR RAIPUR
Address: MADAN COMPLEX,SHAKTI NAGAR,RAIPUR,DISTT.RAIPUR.CHHATTISGARH 492007
City: RAIPUR
District: RAIPUR
State: **CHANDIGARH** *(Incorrect, It should be CHHATTISGARH)*

### Example 4: UTIB0000139
Branch Name: RAIPUR (CHHATISGARH)
Address: OPP NEW BUS STAND JEEVAN BIMA MARG  PANDRI
City: RAIPUR
District: RAIPUR
State: **CHANDIGARH** *(Incorrect, It should be CHHATTISGARH)*

**Comment by captn3m0** [comment]
This is corrected in the new RBI sheets, will be updated alongside the next release.
