### ISSUE TITLE
UPI Enabled Flag

### ISSUE THREAD

**Issue by srikanthlogic** [razorpay/ifsc#126]
* Add UPI enabled as true for all issuers in banks.json 
* [RSS Feed](https://api.apify.com/v1/tvGrw2SdtEZNDaZiZ/crawlers/bnCqzkRJ3PGJ5CRLG/lastExec/results?token=hHrS6MEQNqoqyZxwHmgqZaemK&format=rss&status=SUCCEEDED&ui=1) from NPCI website.
* Add PSP handles if possible.

**Comment by captn3m0** [comment]
PSP handles are split b/w 2 different pages: https://www.npci.org.in/upi-live-members and https://www.npci.org.in/upi-PSP%263rdpartyApps

**Comment by captn3m0** [comment]
@srikanthlogic Which URL are you using for the feed?

**Comment by srikanthlogic** [comment]
I am using upi-live-members URL for the feed. I think that is sufficient to capture issuer banks which is needed to add UPI support flag. 

Adding 3rd party PSP will inject non banks which isn't the focus here, although might be useful to build VPA handler database that is queryable

**Comment by captn3m0** [comment]
There are banks on the list which don't even have a 4 character code (such as `Langpi Dehangi Rural Bank`). What does it even mean for such a bank to have UPI support?

**Comment by VISHALDEEPSAGAR** [comment]
how to create Ifsc code website

**Comment by captn3m0** [comment]
Looks like `Langpi Dehangi Rural Bank` is no longer on the list, despite still being active on UPI. Doesn't give me much confidence on this.

**Comment by captn3m0** [comment]
Working towards this in https://github.com/razorpay/ifsc/pull/161

**Comment by captn3m0** [comment]
This is mostly resolved, except that the negative flag is not set currently (no `upi` key instead of `upi: false`).

Should show up in the next release.

**Comment by captn3m0** [comment]
`UPI: false` is implemented now. Closing this.

https://ifsc.razorpay.com/TAUB0001030
