### ISSUE TITLE
version problem

### ISSUE THREAD

**Issue by kartik3112** [razorpay/ifsc#130]
Unable to install razorpay/ifsc after updating laravel, causing error because it requires php-http/httplug version 1.0 and i have latest version 2.0, and i can't degrade, thus package cannot be installed error.
![image](https://user-images.githubusercontent.com/17043724/59853226-0d57ae80-938e-11e9-9b40-7d4a0482a2b4.png)

**Comment by kartik3112** [comment]
it is not reflected yet on packagist
![image](https://user-images.githubusercontent.com/17043724/59965816-a7575c80-9530-11e9-82ea-969461e1398f.png)

**Comment by kartik3112** [comment]
Dear,

It is not reflected yet on packagist.

**Comment by captn3m0** [comment]
The next 1.4.4 release (pending today/tomorrow) will have this covered.
