### ISSUE TITLE
Change CSV delimiter

### ISSUE THREAD

**Issue by yolossn** [razorpay/ifsc#134]
From the next release please change the delimiter for CSV as the `ADDRESS` column contains `,` in the values and it needs manual efforts to clean the data.

**Comment by captn3m0** [comment]
The CSV Spec covers this: [(Section 2.6)](https://tools.ietf.org/html/rfc4180#section-2)
> 
>    6.  Fields containing line breaks (CRLF), double quotes, and commas
>        should be enclosed in double-quotes.  For example:
> 
>        "aaa","b CRLF
>        bb","ccc" CRLF
>        zzz,yyy,xxx

If you have a row where an address with comma wasn't quoted, please provide the following:

1. Release Version
2. File Name
3. Row Number
