### ISSUE TITLE
Getting IFSC Code from Bank Name and Branch

### ISSUE THREAD

**Issue by bharadhwaj** [razorpay/ifsc#137]
I am using this package for Nodejs. I would like to have a reverse feature of what we are doing now. 

You choose 
- Bank Name 
- State
- District
- Branch

Then we get the output as IFSC code of the matching branch of the bank.

Is that in your to-do list?

**Comment by akashsguptag** [comment]
> I am using this package for Nodejs. I would like to have a reverse feature of what we are doing now.
> 
> You choose
> 
> * Bank Name
> * State
> * District
> * Branch
> 
> Then we get the output as IFSC code of the matching branch of the bank.
> 
> Is that in your to-do list?

Do you find solution ?

**Comment by bharadhwaj** [comment]
@akashsguptag  No. I found a similar issue opened in another repo by Razorpay. [ifsc-api #41](https://github.com/razorpay/ifsc-api/issues/41) To avoid redundancy, closed this.
