### ISSUE TITLE
Wrond Bank codes YESB0HPB051

### ISSUE THREAD

**Issue by cholarajaa** [razorpay/ifsc#155]
IFSC BANK code is duplicated and not valid in some of the co-operative banks.

Himachal Pradesh State Co-operative Bank -- YESB
Palamoor Co-operative Urban Bank -- UTIB
Sundarlal Sawaji Urban Co-operative Bank -- UTIB

![image](https://user-images.githubusercontent.com/7227078/70703769-c0c6ad80-1cf6-11ea-9e95-e46ec6b2487a.png)

**Comment by VISHALDEEPSAGAR** [comment]
how to make a ifsc code website

**Comment by captn3m0** [comment]
Can you clarify what the issue is here?

`YESB0HPB051` is owned by as per https://www.npci.org.in/national-automated-clearing-live-members-1

**Comment by captn3m0** [comment]
@VISHALDEEPSAGAR This is not a support help forum, please create a new issue if you are facing any issue with the service, or [go elsewhere](https://stackoverflow.com/) if you want to learn web development.
