### ISSUE TITLE
Add method for retrieving BANKCODE offline

### ISSUE THREAD

**Issue by ujjwala2318** [razorpay/ifsc#157]
In the libraries, can you please add a way to fetch BANKCODE offline?

**Comment by captn3m0** [comment]
The `Bank::getDetails('PUNB')` method is completely offline. https://github.com/razorpay/ifsc/blob/2c6cadfce38d813294fa937ee64b8894db9d930e/src/php/Bank.php#L1440-L1458

Which language are you trying this in?

**Comment by ujjwala2318** [comment]
I'm using Ruby. Is that method available in Ruby?
