### ISSUE TITLE
Forbidden Status when the API invocation is from US region 

### ISSUE THREAD

**Issue by jayanthchandra** [razorpay/ifsc#173]
Hi, 

I noticed that when i call the razorpay api from US, i am getting the forbidden status code. The same request works when this is called from Indian Region. 

Is there any filter based on region or is there any other checks ? I could not find any info regarding 403 status in the API doc.

**Comment by captn3m0** [comment]
Can you send me your egress IP please? (email at https://github.com/captn3m0)

**Comment by captn3m0** [comment]
Haven't heard back, closing.
