### ISSUE TITLE
wrong information

### ISSUE THREAD

**Issue by pabitramartha** [razorpay/ifsc#174]
Several IFSC of few banks like Vijaya Bank are erroneous. It seems they have been jumbled up.

**Comment by captn3m0** [comment]
Please provide the exact IFSC and the incorrect details.

**Comment by pabitramartha** [comment]
For example 

This IFSC code belongs to Dibrugarh in Assam but in your data is shows of Ganeshguri. The IFSC of Ganeshhguri Branch in Guwahati point to the the branch of Ambala Cantt in Haryana. The correct IFSC code can be obtained from the RBI database or a simple search. I found this specific error case when it came up in my application. There may be other ones too. Please check. 

Data Snippets from your repo:

"VIJB0008002": {
    "IFSC": "VIJB0008002",
    "BRANCH": "GANESHGURI",
    "CENTRE": "GUWAHATI",
    "DISTRICT": "KAMRUP METROPOLITAN",
    "STATE": "ASSAM",
    "ADDRESS": "1ST FLOOR DHRUBA MARKET, GANESHGURI CHARIALI G S ROAD,GUWAHATI,DIST-KAMRUP(METRO)",
    "CONTACT": "00",
    "BANK": "VIJAYA BANK",
    "UPI": true,
    "RTGS": true,
    "NEFT": false,
    "IMPS": true,
    "MICR": null
  },
and 

"VIJB0008019": {
    "IFSC": "VIJB0008019",
    "BRANCH": "AMBALA CANTT,HARYANA",
    "CENTRE": "AMBALA",
    "DISTRICT": "AMBALA",
    "STATE": "HARYANA",
    "ADDRESS": "4261-63,CROSS NO 2, NICHOLSON ROAD, BEHIND B D SCHOOL, AMBALA CANTT,HARYANA, 133001",
    "CONTACT": null,
    "BANK": "VIJAYA BANK",
    "UPI": true,
    "RTGS": true,
    "NEFT": false,
    "IMPS": true,
    "MICR": null
  },

**Comment by captn3m0** [comment]
This is already corrected in upcoming release, because RBI's website fixed it. GANESHGURI is what was present in the last release on the RBI website.
