### ISSUE TITLE
Undefined index: CITY 

### ISSUE THREAD

**Issue by sagarpatel9697** [razorpay/ifsc#175]
When i try to fetch bank detail with UTIB0000003 IFSC code. Script throws error to me something like below:

**ErrorException: Undefined index: CITY in file /vendor/razorpay/ifsc/src/php/Entity.php on line 27** 

Let me know if you need any further assistance.
Thanks

**Comment by captn3m0** [comment]
Will try to get this fixed in the upcoming release. Since this is a RTGS/IMPS only branch, we don't accurately know the CITY of the branch.

**Comment by captn3m0** [comment]
Resolved in 1.5.1.

**Comment by captn3m0** [comment]
@sagarpatel9697 Thanks for reporting this. I've added tests to ensure this doesn't happen again with other fields.
