### ISSUE TITLE
Validation Issue with IFSC Dataset for Banks having branch codes that involve string

### ISSUE THREAD

**Issue by syedsaadh** [razorpay/ifsc#178]
There is validation issue for banks with string as branch code

### Reproduction of Issue: 
IDIB000A001
URBN00000B1

```js
var ifsc = require("ifsc") // v 1.51

ifsc.fetchDetails('IDIB000C122').then(function(res) {
   console.log(res);
}).catch(e => console.log(e));
```
### Response
Invalid IFSC Code

The IFSC dataset contains branch codes with 6 characters instead it should contain 7 characters.
The Validation Code is checking 7 characters to 6 characters so for each branch code where characters are mixed the validation issue persists.

Dataset: IFSC.json

**Comment by captn3m0** [comment]
Was an issue with the published version of the package having an out-of-date code.

I've pushed `1.5.1-1` with the fix, and added this specific IFSC to the tests.
