### ISSUE TITLE
SYNB0003032 - does not have any city associated with it

### ISSUE THREAD

**Issue by impuneet** [razorpay/ifsc#179]
https://ifsc.razorpay.com/SYNB0003032

City is not presented in the schema

{"BRANCH":"MALAKPET, HYDERABAD","CENTRE":"HYDERABAD","DISTRICT":"HYDERABAD","STATE":"ANDHRA PRADESH","ADDRESS":"16-10-33 SATYA HOSPITAL MALAKPET HYDERABAD ANDHRA PRADESH","CONTACT":"04024547633","UPI":true,"RTGS":true,"CITY":"HYDERABAD","NEFT":true,"IMPS":true,"MICR":"","BANK":"Syndicate Bank","BANKCODE":"SYNB","IFSC":"SYNB0003032"}

**Comment by captn3m0** [comment]
Should be resolved now. A deployment was pending, and the release was not rolled out completely.
