### ISSUE TITLE
Wrong Address and branch name

### ISSUE THREAD

**Issue by sg773** [razorpay/ifsc#182]
IFSC - VIJB008007

wrong entry
VIJAYA BANK | VIJB0008007 | JAMMU AIRPORT ,JAMMU & KASHMIR | JAMMU | JAMMU | JAMMU AND KASHMIR | JAMMU AIRPORT EXTN COUNTER,JAMMU & KASHMIR |   | true | true | JAMMU | true |   | true

**Comment by captn3m0** [comment]
No longer a valid IFSC. (Missing in both the [NEFT](https://rbidocs.rbi.org.in/rdocs/content/docs/68774.xlsx) and [RTGS](https://rbidocs.rbi.org.in/rdocs/RTGS/DOCs/RTGEB0815.xlsx) datasets).

Closing.
