### ISSUE TITLE
Wrong Data for IFSC code BKID0008463

### ISSUE THREAD

**Issue by thefoodiecoder** [razorpay/ifsc#185]
**Data from API:**

{
        "IMPS": true,
        "CITY": "SIRSI",
        "ADDRESS": "BANK OF INDIA,SIRSI BRANCH, 3, KAMAT PLAZA, T.S.T. ROAD, SIRSI-581402",
        "BRANCH": "SIRSI BRANCH",
        "UPI": true,
        "STATE": "KARNATAKA",
        "DISTRICT": "UTTAR KANNAD",
        "MICR": "",
        "RTGS": true,
        "NEFT": true,
        "CONTACT": "",
        "CENTRE": "SIRSI",
        "BANK": "Bank of India",
        "BANKCODE": "BKID",
        "IFSC": "BKID0008463"
    }

**Expected Data:**

Address: BANK OF INDIA CHIKKABALLAPUR 2ND CROSS OPO ROAD 28TH WARD CHIKKABALLAPUR CHIKKABALLAPUR DIST BANGALORE KARNATAKA STATE 562101
State: KARNATAKA
District: BANGALORE URBAN 
Branch: CHIKBALLAPUR

**Comment by thefoodiecoder** [comment]
Closing the issue as publically the data is different but the RBI website is having same record as the API.

**Comment by thefoodiecoder** [comment]
**Sorry closed by mistake.** 

The data is not matching what is on RBI website

Reference: https://www.rbi.org.in/Scripts/IFSCDetails.aspx?pkid=179151

**Comment by thefoodiecoder** [comment]
Any updates?

**Comment by captn3m0** [comment]
The details come from the RBI website itself: https://rbidocs.rbi.org.in/rdocs/RTGS/DOCs/RTGEB0815.xlsx (Linked at https://www.rbi.org.in/scripts/FAQView.aspx?Id=65)

Can't do anything here, perhaps reach out to RBI or the banks to get this corrected.
