### ISSUE TITLE
Gives the wrong IFSC code data

### ISSUE THREAD

**Issue by josephmiller2000** [razorpay/ifsc#187]
https://ifsc.razorpay.com/ALLA0211284

Which gives wrong IFSC code data.

Here is the screenshot attachment from. RBI website data "https://rbidocs.rbi.org.in/rdocs/content/docs/68774.xlsx"

![Snap_Shot_00834](https://user-images.githubusercontent.com/24210340/82126162-7925df80-97c8-11ea-92a7-d273ff3c632a.png)

**Comment by captn3m0** [comment]
The details come from the RBI website itself: https://rbidocs.rbi.org.in/rdocs/RTGS/DOCs/RTGEB0815.xlsx (Linked at https://www.rbi.org.in/scripts/FAQView.aspx?Id=65)

Can't do anything here, perhaps reach out to RBI or the banks to get this corrected.
