### ISSUE TITLE
Wrong Data for IFSC code PUNB0428100

### ISSUE THREAD

**Issue by mubarakedp** [razorpay/ifsc#189]
Json data from API (https://ifsc.razorpay.com/PUNB0428100)

{"CITY":"**KUTHUPARAMBA**","MICR":"","CONTACT":"04902361321","STATE":"KERALA","ADDRESS":"17/306(47), **MALABAR PLAZA KANNUR ROAD, KUTHUPARAMBA, KANNUR DISTT, KERALA** 670643","CENTRE":"KUTHUPARAMBA","UPI":true,"RTGS":true,"DISTRICT":"CANNUR","IMPS":true,"NEFT":true,"BRANCH":"KUTHUPARAMBA","BANK":"Punjab National Bank","BANKCODE":"PUNB","IFSC":"PUNB0428100"}

Expected Data:

Address: WANDOOR ROAD KALIKAVU KERALA 676525
State: KERALA
District: **MALAPURAM** (Click here for all the branches of "PUNJAB NATIONAL BANK" in "MALAPURAM " District)
Branch: **KALIKAVU**

**Comment by captn3m0** [comment]
The details come from the RBI website itself: https://rbidocs.rbi.org.in/rdocs/RTGS/DOCs/RTGEB0815.xlsx (Linked at https://www.rbi.org.in/scripts/FAQView.aspx?Id=65)

Can't do anything here, perhaps reach out to RBI or the banks to get this corrected.
