### ISSUE TITLE
Incorrect Branch Info for the given IFSCs

### ISSUE THREAD

**Issue by veedhee** [razorpay/ifsc#191]
1. BKID0002111:
Shows "Infocity Gandhinagar". Should be "Thaltej Ahmedabad"

2. PUNB0408100
Shows "Prashant Vihar". Should be "Paschim Vihar"

**Comment by captn3m0** [comment]
The details come from the RBI website itself: https://rbidocs.rbi.org.in/rdocs/RTGS/DOCs/RTGEB0815.xlsx (Linked at https://www.rbi.org.in/scripts/FAQView.aspx?Id=65)

Can't do anything here, perhaps reach out to RBI or the banks to get this corrected.
