### ISSUE TITLE
Inconsistencies in data returned by IFSC API and RazorPay documentation

### ISSUE THREAD

**Issue by nsinghal12** [razorpay/ifsc#196]
The hosted IFSC toolkit API returns incorrect bank code for the following banks: `USFB`, `PUNB_R`, and `BARB_R`

For example, the bank code returned for [UJVN0000001](https://ifsc.razorpay.com/UJVN0000001) and [UJVN0001008](https://ifsc.razorpay.com/UJVN0001008) are different (USFB in former, and UJVN in latter).

Refer to the latest [banks.json](https://github.com/razorpay/ifsc/releases/download/1.5.5/banks.json). The details for bank USFB are given as:

```json
"USFB": {
    "code": "USFB",
    "type": "SFB",
    "ifsc": "UJVN0000001",
    "micr": "560761002",
    "iin": "508991",
    "apbs": true,
    "ach_credit": true,
    "ach_debit": true,
    "nach_debit": false,
    "upi": true
  }
```

There is no bank listed with bank code `UJVN` in the [banks.json](https://github.com/razorpay/ifsc/releases/download/1.5.5/banks.json) file.

Also, there is no bank listed with bank code `UJVN` in [RazorPay documentation for E-Mandate](https://razorpay.com/docs/recurring-payments/bank-options/) 

This inconsistency causes issues for clients as we cannot validate the bank against the master list.

**Comment by captn3m0** [comment]
The `banks.json` file is is maintained against [this page](https://www.npci.org.in/what-we-do/nach/live-members/live-banks). The UJVN0000001 -> UFSB mapping comes from the above link.

The `UJVN0001008` data comes from RBI, which doesn't provide a mapping by itself so the first 4 characters are picked (UJVN).

The "bank detection" as such is not-perfect - but does get better over time. I've added `UJVN` to our list of custom sublet prefixes, so this should be resolved on the API once the next release goes out.

Thanks for creating this issue. The `PUNB_R` issue is more complicated, but I'll get it tracked internally.
