### ISSUE TITLE
Add support for Dart & Flutter

### ISSUE THREAD

**Issue by Maddoxx88** [razorpay/ifsc#199]
Can someone assign it to me? @captn3m0 @asldevi @ace03uec @rubish @shashankkumar

**Comment by captn3m0** [comment]
Can you clarify what functionality are you looking for? The API should work nicely from either of these.

**Comment by Maddoxx88** [comment]
Support for API in Flutter Apps and for any app built with Dart.

**Comment by captn3m0** [comment]
You can just use the [http](https://pub.dev/packages/http) package in Dart to make a request to https://ifsc.razorpay.com.

**Comment by Maddoxx88** [comment]
Already created an app using it [here](https://github.com/Maddoxx88/ifsc-validator)
Was thinking of contributing in the documentation/readme of this project.

**Comment by captn3m0** [comment]
Looks great! Feel free to file a PR if you have suggestions for documentation fixes.

**Comment by Maddoxx88** [comment]
> Looks great! Feel free to file a PR if you have suggestions for documentation fixes.

Cool
