### ISSUE TITLE
Provide MICR codes in JSON response

### ISSUE THREAD

**Issue by akshaybhalotia** [razorpay/ifsc#2]

**Comment by captn3m0** [comment]
The issue with MICR codes was that they were wildly in disseparate formats in the excel files. (different column numbers and names). This would mess up the contact/address field earlier, so i just dropped it.

**Comment by shashankkumar** [comment]
Should we close this @captn3m0 ?

**Comment by captn3m0** [comment]
No, we have the data for some of the branches. We need to write a better filter that parses and formats them correctly, similar to how we resolved #3

**Comment by awanishraj** [comment]
No MICR for KKBK0000473

**Comment by captn3m0** [comment]
The Kotak sheet provided by RBI does not have it: http://rbidocs.rbi.org.in/rdocs/Content/DOCs/IFCB2009_46.xlsx

Since the API now reasonable provides MICR codes wherever available, I'm closing this issue.

**Comment by awanishraj** [comment]
This website seems to have the data though - https://ifsc.bankifsccode.com/KKBK0000473
Is there a different dataset?

**Comment by captn3m0** [comment]
The RBI website does seem to have it: https://www.rbi.org.in/Scripts/MICRDetails.aspx?Mpkid=74378

But doesn't provide it in the dataset. I've raised it with RBI.

**Comment by captn3m0** [comment]
Raised it with RBI.
