### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by isharad28** [razorpay/ifsc#203]
Access to XMLHttpRequest at 'http://ifsc.datayuge.com/api/v1/KKBK0005289' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

Please help in this

**Comment by captn3m0** [comment]
You're using HTTP, instead of https.

**Comment by Arjun0o** [comment]
I am experiencing this issue as well. @isharad28 , were you able to solve it?

**Comment by isharad28** [comment]
Use https instead of http

**Comment by isharadgrene22** [comment]
> I am experiencing this issue as well. @isharad28 , were you able to solve it?
try using  fetch  rather than  razor pay dependency
fetch("https://ifsc.datayuge.com/api/v1/"+formik.values.IFSC, requestOptions)
  .then(response => response.text())

**Comment by Arjun0o** [comment]
@isharad28 , I am using https instead of http. CORS is enabled at the server as well. Can you share the code if it's possible? Thanks

**Comment by isharadgrene22** [comment]
> @Arjun0o  , I am using https instead of http. CORS is enabled at the server as well. Can you share the code if it's possible? Thanks, try using fetch rather than razor pay dependency 
**fetch("https://ifsc.datayuge.com/api/v1/"+formik.values.IFSC, requestOptions)
.then(response => response.text())**
