### ISSUE TITLE
CORS issue on angular

### ISSUE THREAD

**Issue by aseemKetto** [razorpay/ifsc#205]
Hi ,
I am facing the following issue.
`_Access to XMLHttpRequest at 'https://ifsc.razorpay.com/KARB0000001' from origin 'http://localhost:4400' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource._`.
Can you please help me with the same?

**Comment by captn3m0** [comment]
CORS headers are correctly set. Closing this for now. Please reopen if you're still facing this.

```
curl -I https://ifsc.razorpay.com/KARB0000001
HTTP/1.1 200 OK
Date: Thu, 06 May 2021 06:29:50 GMT
Content-Type: application/json
Content-Length: 378
Connection: keep-alive
Access-Control-Allow-Origin: *
```
