### ISSUE TITLE
banknames.json file missing in release after v1.5.5

### ISSUE THREAD

**Issue by rishabhc32** [razorpay/ifsc#212]
The file `banknames.json` which maps bank codes to bank names is not present in all the releases after v1.5.5. But the same file is present in the source code `src/banknames.json`. Is this intended or there is a bug in build/release pipeline?

**Comment by captn3m0** [comment]
Updated the current latest release to add banknames.json.

For future reference, the file is committed as part of the repo, so the latest version can always be found at https://github.com/razorpay/ifsc/blob/master/src/banknames.json
