### ISSUE TITLE
Bank Name null in release 

### ISSUE THREAD

**Issue by mining016** [razorpay/ifsc#221]
#220 
In release 1.5.12 the csv file contains NULL in bank name for many IFSC codes. 
For example 
ABHY0065099
ABNA0000001
ADCC00000SC
BNPA0009066
FINO00000SC
almost 304 IFSC codes are having this issue.

**Comment by mining016** [comment]
https://github.com/razorpay/ifsc/releases/download/1.5.12/IFSC.csv
Link to the asset

**Comment by captn3m0** [comment]
Thanks for the report.
