### ISSUE TITLE
Showing Wrong Bank Name

### ISSUE THREAD

**Issue by bunnyrockz** [razorpay/ifsc#222]
Link: https://ifsc.razorpay.com/PUNB0392700
Output: {"BRANCH":"DAULATPUR","CENTRE":"DAULATPUR","DISTRICT":"UNA","STATE":"HIMACHAL PRADESH","ADDRESS":"DAULATPUR, UNA  HP 176038","CONTACT":"01976265167","UPI":true,"RTGS":true,"CITY":"DAULATPUR","MICR":"110024187","NEFT":true,"IMPS":true,"SWIFT":"","BANK":"Punjab National Bank","BANKCODE":"PUNB","IFSC":"PUNB0392700"}

Original Bank: PNB, Dilshad Garden

**Comment by captn3m0** [comment]
This is correctly reported now.
