### ISSUE TITLE
Syndicate Bank IFSC codes

### ISSUE THREAD

**Issue by bijjuchow** [razorpay/ifsc#243]
Now that Syndicate bank is merged with Canara bank, its IFSC codes are no longer valid as per this https://canarabank.com/IFSC.html.
Please remove these IFSC codes from accessibility.

Eg: SYNB0000445 is now CNRB0010445 and SYNB0000445 is not valid.

**Comment by captn3m0** [comment]
These were dropped in the 1.6.1 release (Aug 2021).
