### ISSUE TITLE
SBI IFSC codes missing

### ISSUE THREAD

**Issue by build3r** [razorpay/ifsc#264]
The data is missing some IFSC codes in remote parts of India.
For example the IFSC code `SBIN0019211` is valid and corresponds to branch SBI Gangtok, But the API gives 404 response
Can we please update the data sets?

[https://ifsc.razorpay.com/SBIN0019211](https://ifsc.razorpay.com/SBIN0019211)  -- returns Not Found
[https://ifsc.bankifsccode.com/SBIN0019211](https://ifsc.bankifsccode.com/SBIN0019211)  --valid

**Comment by captn3m0** [comment]
This is answered in the FAQ: https://github.com/razorpay/ifsc/wiki/FAQ#the-api-says-an-ifsc-code-is-invalid-while-my-bank-says-it-is-correct

The IFSC is no longer valid, as can be confirmed by the RBI website. This branch was removed by SBI in Nov 2021: https://github.com/razorpay/ifsc/releases/tag/v2.0.2 (Click "Exact IFSC Diff").
