### ISSUE TITLE
Trailing special characters in certain IFSC codes' branch/address details

### ISSUE THREAD

**Issue by tekina** [razorpay/ifsc#29]
`GET https://ifsc.razorpay.com/ICIC0000001`
returns
`{"BANK":"ICICI Bank","IFSC":"ICIC0000001","BRANCH":"CHENNAI - CENOTAPH ROADâ”¬Ã¡","ADDRESS":"1, CENOTAPH ROAD, CHENNAI.â”¬Ã¡","CONTACT":null,"CITY":"CHENNAI","DISTRICT":"CHENNAI","STATE":"TAMIL NADU"}`

As can be seen, there are some trailing special characters in `BRANCH` and `ADDRESS` values. I'm not sure if this is due to the way the data is picked or with the dataset itself. 
So far I've noticed this only for certain ICICI codes, so could be an issue with the dataset for these entries.
Either way, would like to know if this is something which can be fixed.

**Comment by captn3m0** [comment]
Thanks for the report. This is how it looks like in the source document:

![image](https://user-images.githubusercontent.com/584253/28166152-7ed23ac0-67f4-11e7-8108-b63cbff8d191.png)

You can verify the same at http://rbidocs.rbi.org.in/rdocs/Content/DOCs/IFCB2009_35.xlsx

**Comment by captn3m0** [comment]
Looks like an issue with the generation of the excel file itself, which is out of our scope. Likely it is a space character, but I don't want to add special handling for such cases.

**Comment by captn3m0** [comment]
Marking this as closed

**Comment by captn3m0** [comment]
RBI doesn't seem to be keen to fix these, so these are now cleaned up in the release. Accuracy is not guaranteed, but if you notice an issue starting [from 1.5.13 release](https://github.com/razorpay/ifsc/releases/tag/1.5.13) - please create a new issue.

Note that the changes aren't live at ifsc.razorpay.com yet, but should be there soon.
