### ISSUE TITLE
Contact field is probably being stored as a float number

### ISSUE THREAD

**Issue by steelrooter** [razorpay/ifsc#3]
Response for https://ifsc.razorpay.com/HDFC0001993

{"BANK":"HDFC BANK","IFSC":"HDFC0001993","BRANCH":"HSR LAYOUT","ADDRESS":"HSR LAYOUT NO.446, 17TH CROSS 4TH SECTOR, HSR LAYOUT BANGALORE KARNATAKA", **"CONTACT":9945863333.0** ,"CITY":"BANGALORE","DISTRICT":"BANGALORE URBAN","STATE":"KARNATAKA"}

**Comment by captn3m0** [comment]
I always assumed that was because of the RBI excel sheets itself. Maybe we should force it to a string.

**Comment by steelrooter** [comment]
Do we clean this field while importing?

**Comment by captn3m0** [comment]
Currently, no: https://github.com/razorpay/ifsc/blob/34448ac10832a596cbc6e4758a81deceaa3b3c91/scripts/methods.rb

Should be easy enough

**Comment by captn3m0** [comment]
Currently, no: https://github.com/razorpay/ifsc/blob/34448ac10832a596cbc6e4758a81deceaa3b3c91/scripts/methods.rb

Should be easy enough

**Comment by captn3m0** [comment]
working on this
