### ISSUE TITLE
Bad characters in json / API response

### ISSUE THREAD

**Issue by adsahay** [razorpay/ifsc#32]
There are some bad characters in the data. 

E.g., in `ICIC.json` we find:

```
  "ICIC0000001": {
    "BANK": "ICICI BANK LIMITED",
    "IFSC": "ICIC0000001",
    "BRANCH": "CHENNAI - CENOTAPH ROAD┬á",
    "ADDRESS": "1, CENOTAPH ROAD, CHENNAI.┬á",
    "CONTACT": null,
    "CITY": "CHENNAI",
    "DISTRICT": "CHENNAI",
    "STATE": "TAMIL NADU"
  },
  "ICIC0000002": {
    "BANK": "ICICI BANK LIMITED",
    "IFSC": "ICIC0000002",
    "BRANCH": "BANGALORE - M G ROAD┬á",
    "ADDRESS": "ICICI BANK TOWERS, 1, COMMISSARIAT ROAD, GROUND FLOOR, BANGALORE┬á560025.┬á",
    "CONTACT": null,
    "CITY": "BANGALORE",
    "DISTRICT": "BANGALORE URBAN",
    "STATE": "KARNATAKA"
  }
```

These bad characters are also part of the GET API responses.

**Comment by captn3m0** [comment]
This is a known issue at RBI end: https://github.com/razorpay/ifsc/issues/29

**Comment by captn3m0** [comment]
Please reach out to RBI here: https://www.rbi.org.in/Scripts/helpdesk.aspx

**Comment by captn3m0** [comment]
RBI doesn't seem to be keen to fix these, so these are now cleaned up in the release. Accuracy is not guaranteed, but if you notice an issue starting [from 1.5.13 release](https://github.com/razorpay/ifsc/releases/tag/1.5.13) - please create a new issue.

Note that the changes aren't live at ifsc.razorpay.com yet, but should be there soon.
