### ISSUE TITLE
Missing IFSC code -> SBIN0064340

### ISSUE THREAD

**Issue by GursimarSinghChawla** [razorpay/ifsc#334]
The SBI branch IFSC code -> SBIN0064340 is missing from the list.
This is a valid bank as seen on RBI bank website.
<img width="718" alt="Screenshot 2023-05-24 at 11 16 50 AM" src="https://github.com/razorpay/ifsc/assets/95013873/fe8d1b2f-048c-4a4e-af21-fb954ca356d5">

Looking forward to a response.

**Comment by danishsatkut** [comment]
This issue can be now closed. IFSC is available now: https://ifsc.razorpay.com/SBIN0064340

![IFSC SBIN0064340](https://github.com/razorpay/ifsc/assets/394239/8970a442-5b25-4769-9917-dc25b9e47941)
