### ISSUE TITLE
This below IFSC code is showing "Not found"

### ISSUE THREAD

**Issue by planetwebsolution** [razorpay/ifsc#39]
I've found this IFSC code valid but API is showing "Not Found". IFSC code is : SBIN0011395

**Comment by captn3m0** [comment]
@planetwebsolution Can you clarify what is your criteria for valid?

The [RBI website Excel for RBI](https://rbidocs.rbi.org.in/rdocs/Content/DOCs/IFCB2009_68.xlsx) does not include this IFSC.

Ref: https://www.rbi.org.in/Scripts/bs_viewcontent.aspx?Id=2009

**Comment by captn3m0** [comment]
No response, marking as closed.
