### ISSUE TITLE
php composer installation failed

### ISSUE THREAD

**Issue by whfamily2006** [razorpay/ifsc#45]
PC> composer require razorpay/ifsc
Using version ^1.0 for razorpay/ifsc
./composer.json has been updated
Loading composer repositories with package information                                                    Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - razorpay/ifsc 1.0.9 requires php-http/client-implementation ^1.0 -> no matching package found.
    - razorpay/ifsc 1.0.8 requires php-http/client-implementation ^1.0 -> no matching package found.
    - razorpay/ifsc 1.0.7 requires php-http/client-implementation ^1.0 -> no matching package found.
    - razorpay/ifsc 1.0.6 requires php-http/client-implementation ^1.0 -> no matching package found.
    - razorpay/ifsc 1.0.5 requires php-http/client-implementation ^1.0 -> no matching package found.
    - razorpay/ifsc 1.0.4 requires php-http/client-implementation ^1.0 -> no matching package found.
    - razorpay/ifsc 1.0.3 requires php-http/client-implementation ^1.0 -> no matching package found.
    - razorpay/ifsc 1.0.2 requires php-http/client-implementation ^1.0 -> no matching package found.
    - razorpay/ifsc 1.0.11 requires php-http/client-implementation ^1.0 -> no matching package found.
    - razorpay/ifsc 1.0.10 requires php-http/client-implementation ^1.0 -> no matching package found.
    - razorpay/ifsc 1.0.1 requires php-http/client-implementation ^1.0 -> no matching package found.
    - razorpay/ifsc 1.0.0 requires php-http/client-implementation ^1.0 -> no matching package found.
    - Installation request for razorpay/ifsc ^1.0 -> satisfiable by razorpay/ifsc[1.0.0, 1.0.1, 1.0.10, 1.0.11, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8,
 1.0.9].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

and my stability setting is as follows: 

```
"minimum-stability" : "stable"
```
I am installing this with laravel 5.3 application. Can you please correct me where I am wrong?

**Comment by captn3m0** [comment]
You need to install one of the packages from this list as well: https://packagist.org/providers/php-http/client-implementation
