### ISSUE TITLE
Double IFSC codes in bankname.json file

### ISSUE THREAD

**Issue by whfamily2006** [razorpay/ifsc#49]
{
FIRN : Firstrand Bank
FIRX : Firstrand Bank
}

{
KANG : Kangra Co-operative Bank
KCOB : Kangra Co-operative Bank
}

{
SJSB : Solapur Janata Sahakari Bank
SJSX : Solapur Janata Sahakari Bank
}

So many banks with ends with X what is meaning of that bank code?

**Comment by captn3m0** [comment]
Unfortunately, RBI and NPCI have conflicting naming schemes. The X is for co-operative banks that do not have direct access to the NEFT network.

Sometimes, these banks can later on get access and get their own IFSC codes. That is the case with the above banks. However, the old ones are still reflected in NPCI spreadsheets and thus retained.
