### ISSUE TITLE
Get NPM package to parity with PHP

### ISSUE THREAD

**Issue by captn3m0** [razorpay/ifsc#59]
NPM package does not support:

- [Bank Constants](https://github.com/razorpay/ifsc/blob/master/src/php/Bank.php)
- [Fetch Details from API](https://github.com/razorpay/ifsc/blob/master/src/php/Client.php)
- [A proper class for IFSC response](https://github.com/razorpay/ifsc/blob/master/src/php/Entity.php)
- [Get Bank Name method that uses sublet.json](https://github.com/razorpay/ifsc/blob/master/src/php/IFSC.php#L73)

**Comment by nihalgonsalves** [comment]
Happy to help on this one

**Comment by Parikshit-Hooda** [comment]
hey !
can you explain the objective a little more clearly? i dont understand it.
As far as i can understand, you want me to port code from php to nodejs.. but the point is ;i dont know php. How do you propose we proceed from here?

**Comment by captn3m0** [comment]
Hi @nihalgonsalves, thanks for the offer 👍. We're doing this as part of [CMoC](https://github.com/clusterinnovationcentre/CMoC) and @Parikshit-Hooda will be taking this up.

More details on the task:

Right now there is a feature parity mismatch between the PHP package (which we use internally) and the NPM package. Mostly because we (@Razorpay) use the PHP package in our codebase, and the NPM one is not.

The idea is to have the same features (don't think in terms of porting of code) in the NPM side. The NPM package already supports client-side validations ([source](https://github.com/razorpay/ifsc/blob/master/src/node/index.js)), and needs more things.

I'd suggest going in the following order:

- Adding support for fetching details from the API. This would involve depending on another package like `request` and returning the correct response (or an error). Input = IFSC code, response = object containing details from the [IFSC API](https://ifsc.razorpay.com/IBKL01058MD). This method is already stubbed out in the codebase as "not implemented"
- Adding a getBankCode method. The initial functionality is basic (return first four characters), and then you need to read the PHP code to understand the rest (reading sublet.json, and using it correctly)

I'd ideally want the first to be done using promises (since it is a network request), and tests as well.

**Comment by Parikshit-Hooda** [comment]
i am on it.  Can I communicate with you on whatsapp too?

**Comment by captn3m0** [comment]
Other than sublet support, the rest are done.

https://github.com/razorpay/ifsc#support-matrix

Closing this, and creating a new ticket just for that.
