### ISSUE TITLE
Create wercker task and publish newer Hex packages

### ISSUE THREAD

**Issue by nihalgonsalves** [razorpay/ifsc#60]
- [x] Create razorpay user and add as admin 
- [x] Create wercker task

**Comment by captn3m0** [comment]
I'd created https://hex.pm/users/razorpay.

Will go through the rest

**Comment by nihalgonsalves** [comment]
Added as admin https://hex.pm/packages/ifsc

**Comment by captn3m0** [comment]
Thanks! If you wanna take a stab at wercker, you can create a local branch on this repo to try. I'll get around to it sometime this week otherwise.

**Comment by nihalgonsalves** [comment]
Here: https://github.com/razorpay/ifsc/pull/61 - I have no access to Wercker, can you please check if the build works and then add it as a required status check?

**Comment by nihalgonsalves** [comment]
Resolved by https://github.com/razorpay/ifsc/commit/737eb8a7a1757e0a9fcd6727aca47ec6ed7dfdb9
