### ISSUE TITLE
Two new fields in the CSV file?

### ISSUE THREAD

**Issue by vivekfantain** [razorpay/ifsc#92]
IFSC.CSV has two new fields added in 1.3 that didn't exist in the previous release?

**Comment by captn3m0** [comment]
I'm looking at the file in 1.2.3 and 1.3.0 releases and I see no difference in the headers.

The `RTGS` field was added a while back though, but it was a backward-compatible change to both the data dumps and the API as well.

**Comment by captn3m0** [comment]
Closing this. Additional fields are not considered breaking changes. (The 1.4.0 release adds 2 more).
