### ISSUE TITLE
Composer dependency resolver issue

### ISSUE THREAD

**Issue by waqas-mehmood-pk** [razorpay/ifsc#97]
Please review the Problem No. 2 in following image. 

![image](https://user-images.githubusercontent.com/9881496/50611695-503bcd80-0ea5-11e9-84db-1b23dda7614a.png)

I am installed this package with laravel 5.3. I have also try to fix the version of razorpay library as 1.0 which was working perfectly previously. 

Any help/guidance needed..

**Comment by captn3m0** [comment]
Please see http://docs.php-http.org/en/latest/httplug/users.html#composer-fails

As an easy solution you can run:

`composer require php-http/curl-client razorpay/ifsc`

You can replace `php-http/curl-client` with any package that provides `php-http/client-implementation`. See https://packagist.org/providers/php-http/client-implementation for a complete list.

I'm leaving this open till it gets documented in our README better.

**Comment by captn3m0** [comment]
Leaving it open till we document this better.
